dist: trusty
sudo: required

language: python

branches:
  only:
    - master

services:
  - docker

before_install:
  - cd blog
  - docker build -f Dockerfile .

install:
  - cd ..
  - mv runtime/ blog-docker/
  - sh blog/entrypoint.sh

script: true

notifications:
  email:
    recipients:
      - suraj.gate2013@gmail.com
    on_success: never
    on_failure: always
