dist: trusty
sudo: required
 

language: python

branches:
  only:
    - master

services:
  - docker

before_install:
  - sudo mv runtime/ /blog-docker/
  - cd blog
  - docker build -f Dockerfile .

install:
  - sh bin/entrypoint.sh

script: true

notifications:
  email:
    recipients:
      - suraj.gate2013@gmail.com
    on_success: never
    on_failure: always
