dist: trusty
sudo: required

language: python

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker-compose up -d

  

install: true

script: true

notifications:
  email:
    recipients:
      - suraj.gate2013@gmail.com
    on_success: never
    on_failure: always
